#@ load("@ytt:data", "data")
#@ load("deploy-tenants.lib.yml", "deploy_steps")
#@ load("deploy-tenants.lib.yml", "get_deployment_job_name")
#@ load("@ytt:template", "template")

name: Self-Hosted Tenants Deploy
"on":
  workflow_run:
    workflows:
      #@ for workflow in data.values.deploy.triggers.workflows:
      - #@ workflow
      #@ end 
    types:
      #@ for condition in data.values.deploy.triggers.conditions:
      - #@ condition
      #@ end
   
jobs:
  version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Get version from git tag
    outputs:
      app_version: ${{ steps.version.outputs.app_version }}
      should_deploy: ${{ steps.version_check.outputs.should_deploy }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout GitHub Action Repos
      uses: daspn/private-actions-checkout@v2
      with:
        actions_list: '[
        "covergo/get-version@v1.6",
        "covergo/get-issue-key@v1.2"
        ]'
        checkout_base_path: ./.github/actions
        app_id: ${{ secrets.PRIVATE_ACTION_APP_ID }}
        app_private_key: ${{ secrets.PRIVATE_ACTION_APP_PRIVATE_KEY }}
    - name: Get jira Ticket slug
      id: issue-key
      uses: ./.github/actions/get-issue-key
    - name: Get version from git tags
      id: version
      uses: ./.github/actions/get-version
    - name: Should deploy check
      shell: bash
      id: version_check
      run: |
        if [[ ${{ steps.version.outputs.app_version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo ::set-output name=should_deploy::true
        fi

  #@ for tenant in data.values.deploy.tenants :
  job: #@ template.replace({get_deployment_job_name(tenant): deploy_steps(data.values.deploy, tenant)})
  #@ end